export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as AllGames } from './AllGames/AllGames'
export { default as GameDetails } from './GameDetails/GameDetails'
export { default as NoPage } from './NoPage/NoPage'
