export { default as Header } from './Header/Header'
export { default as Slider } from './Slider/Slider'
export { default as HeroButton } from './HeroButton/HeroButton'
export { default as Search } from './Search/Search'
export { default as TitleList } from './TittleList/TitleList'
export { default as SingleGame } from './SingleGame/SingleGame'
